### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by edunham** [edunham/ssfgame#1]
- [ ] create pane for account list to show in
- [ ] optional, create events log pane where you can research someone's accounts/salary/routine, or see when a business held a security event, or maybe see when someone changed their routine
- [ ] phishing gets you an account in list in low pane, account can compromise (1% or all) or escalate (compromise network of location they're in while they're in it)
- [ ] * buy wifi pineapple that phishes for you by compromising a location's network??
- [ ] * give people index of suspicion and make it move on failed phish, money take, etc
- [ ] * longer day? time slider to adjust tick length?
- [ ] * sufficiently suspicious people must log out of their accounts, thereby removing them from the list
- [ ] * institutions should have security training where people get more suspicious
- [x] * failing a phish raises their suspicion by 10% of whatever you rolled on the fail
- [ ] * suspicion should degrade over time, maybe slower for higher salaries
- [ ] businesses have coffers and their own suspicion index
- [ ] people going to businesses spend money at them
- [ ] * escalating an account maybe gives you network compromise of  the location the person is at when you escalate it
- [ ] * with a corporate network you can either steal people data or steal the corp's money, and corps have index of suspicion too
- [ ] * failing a corporate exploit is game over because you get caught
- [ ] * decouple own wallet from the timer -- should be two sub-divs or w/e of their container
- [ ] container with wallet and timer should also have title
- [ ] maybe put some credits at the bottom
